language: node_js
node_js:
- node
deploy:
  - provider: s3
    access_key_id: AKIAJIP6U6YGHUHXXFYA
    secret_access_key:
      secure: BEzQ1k6L76cbxVBnsrxtvlwoAjT2m/9UiriO7eN3vbyF7XxJcN0vdslwC0Fkz0FEwsYPFCUiKFL512tTF3z7s4j3Fyr48AA+ZO/INdZOgulY8+87d30BMFJE/UvDygwKQIYDZuv2Dh8r4/nD4y26+wIDBIKSAq6G90h8O6Z8MU1YVG8Ns+QHh8CZZw+tcQ5m0m27PkaoX2xxUzwekuLnnP3Jx3FXNzURRYJqdt234vgBoBywgdYrNovsW5vnMWwwfpp3e2Ncazav9i0JuIpAjRdt6AR7g5+Da3NXgm4Z5UhyCWwcidLzslOv0lXHIRyI0qc512h8nF7leYtge2smWPD7FAfDHEJhOQFUGmnnYyuxRiKavKS8pUr/6rlyHeI8P++/+hoH2k674kdJK2/UjxSw95f80LlId327Zh386A+7vCylX5zf1VhWCq5UvjLok1tK+qte/uIBjQWNw62iIhDTe+Y7pulsY0j2U5UxUPFsi/hwGqiVhf5h1lBzrCWkl8PodRYPmNDGTd0SW3OURTu/ExuyYxg/8Pzs8N8LG/SKCUPOSfHqCIff0i6HXf5GAmJUxrSEdV+Q5zmkJ8JGx5JIlQjM0r4VgjbyR0LWz4+aP6JWePzwnyLzMZXU5MkO1+TNWvhNc5QLD1M/qotxfHbw55rD+1rN2MfomFeuuio=
    bucket: innov8tionfactory.com
    acl: public_read
    region: ca-central-1
    verbose: true
  - provider: azure_web_apps
    site: innov8tionfactory
    verbose: true
  - provider: gcs
    access_key_id: GOOGHGTP3N5A5Z5XKFMEIHUX
    secret_access_key:
      secure: mUwfXWIiZD1EK6zRaisfCPGT23q5ZKIDwkGid1dBthmGmQYTR+E7oyFQckbmETgFfpaaYjP65bHCwx2utvbCLD7qGM/U7wNsdV3rI1/GyfACPygAYuUAVF4GoH+AkqkOupM4Hi0v+vo6CRnlHgubxNWcs+iIZror+8foVeVjmYO8q9z9KKfvrOffsmYnS+dQLy0SI1EF4+SPk3P4BVgKBC4ZtliI7UKJDalDvJZt87efEgAwKrmkDUsel9fy4IitMoctc+oYKk8oYGRqdtefu3pOvhmnk30Ug+QwrxBD3iQunqyHBBYRbC2z5dJkCbwFbCbu/RvMGdQxVjFWZyTC/iTlcYBQ/DqD4RM8R5aivxl4WKnkjGW0kPAxeVo/aWfWQwMWBfndPPIBzu2O+JDPpGadBPNefFUM+X5TJugSmZzT3WaXCKJUWh93dVN9d40lbQ9u06Q7ztA6UfpLSp/loIAd2ZbjwUIWZvP5/vD9aOfY6roAz/ckFtmlXZxBFjl0gnkFnCXAWWpGeBtMVGwoA5dLEfTVg5Rvbdio1ewT9F+5tY5vkYKL0C7JM02DcySwNbHdtW6yX5G8J0RiUdnyiuTLyAj9QTBFAhxAjPv2YgPzfs8B7vKWbOkVFPOkFisJfk49WE/+SyHLR16ghNY26ugeyTYWLQNHV4ykldIVLrU=
    bucket: gcs-eu.innov8tionfactory.com
    verbose: true
branches:
  only:
    master