language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIAJQVPHI2G26EG3K5Q
  secret_access_key:
    secure: IXuje0MZvzRWCKBx29kB2R15mJvC7ce3+5Q/O6e7cvAxb/rwo4cm8gSJEMQO1YccGcOM/Ph8VLHrY8ya6gFJ8VXIt9exJwGySQ8RZnxbJPiKww/0l6xxi9saKKSnakgpn34Y3Y84TPgvYhiHVfmZo/5I/tUFFjQSmH+7SzDQDAkylJII0GY8gSHL1QcUwledjRTLjERx32LzlOE3tnUGjBFqLDI+UGMXPpVQhvtODy8nE//xZbqWoijnQeoez/kL4NZiikWsi/Ry/9kJW4u+NfriYmmbE2p8J7SWIZ0PY7+VwQDGU2+0cIG5zKVNb7T26Z8/D+nYuFBHM9YTHuC7ViOtbkKFjpdqHaSnRnz33C8M1iR/PFImb6kZ8C22EIrrJ2YuvzE9skRdZIeGLLy+cvY8kFbkAxboRLylPvXGXvcEu5gpZxI4NN33Yy4t9BtVf4v0AUDTVD5PsJmAH50Rvhes+z+qjyEqWYJxXsZri8zxmiPIsxThxABRSLRbYBupWkM5aiY43CgjTHD1w1iGFRLkgTOnff0cGeXzW9Y/u7XHAEECsCmFHfgyBrk2vxBrPm2hjHh3cvsvlQNx4XI5nuJjVn1WRUKfAw8W2YhHuDJUdEdWJY/DUfFWaL8OKxA7sl74AwE6aS0Gv3nDk/oCCtuD48Lv41/LP14Oz1kuX94=
  bucket: "innov8tionfactory.com"
  acl: public_read
  region: ca-central-1