language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJQVPHI2G26EG3K5Q
  secret_access_key:
    secure: EZLC2/bEkELORqdutm/qhvmXneBGbU7/uQNG6fFw2ZJBpRT2lJHEYAtF6qf/UnJ/IWKXBKHpybwnWYg9jlixgiKTNQeVqTdsrbabbYhlycnUBlER1fa0v278ykoS9GFDovNuZJYiNDJWpSByGOYlu2z30MFHeYcTWmTUPPC8PDoK0MBksnioRgvMvVUaBUr7bv0BPfHISwFadeRJxLQfJZzNfCugzWI9L4mpUPgtWHu7L8sE26mh/usRIQJ4VnRTa5eFNTp1E1dJHcEQfNouMyIdd+wkSkfv1ZQvkv4Zzb1wae+6aZvoSWaL0J6Uyn5EgWv6nbv4WbpoeOWucIwOHz64/wtHQbQja5QzW7CQzO/8Jf9WdyMjBltNoLm85tafCaKTqJROb+j4eJd1KPs+0LktHbBzYAjR+G7xIhas2LZPLBtDsRe6Ozo3AkvJSypIJOy7pzNoWX0BfSnJ4vKJ2C7kWktCxYDAcKD/iCgYDeewmcUMC4HBxdnvhhFrrmIOfcay7/crem3d+PW8TmxY38FxFPpjIp7Eyu1DST6swGZNC5tlg/lVZVzonT4XvHqX2IuZ/oBD2u8DaIdPkv3WExb7iVhkEx10ToJif2KOG+lK+b++Y2sR1A+zDI4nEC3O+X7ONMAKTgyX0mYR1uCuYkD7xyulmu2zOjJ0C5IKhjg=
  bucket: innov8tionfactory.com
  acl: public_read
  on:
    repo: paulmona/WebSite
