language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJIP6U6YGHUHXXFYA
  secret_access_key:
    secure: BEzQ1k6L76cbxVBnsrxtvlwoAjT2m/9UiriO7eN3vbyF7XxJcN0vdslwC0Fkz0FEwsYPFCUiKFL512tTF3z7s4j3Fyr48AA+ZO/INdZOgulY8+87d30BMFJE/UvDygwKQIYDZuv2Dh8r4/nD4y26+wIDBIKSAq6G90h8O6Z8MU1YVG8Ns+QHh8CZZw+tcQ5m0m27PkaoX2xxUzwekuLnnP3Jx3FXNzURRYJqdt234vgBoBywgdYrNovsW5vnMWwwfpp3e2Ncazav9i0JuIpAjRdt6AR7g5+Da3NXgm4Z5UhyCWwcidLzslOv0lXHIRyI0qc512h8nF7leYtge2smWPD7FAfDHEJhOQFUGmnnYyuxRiKavKS8pUr/6rlyHeI8P++/+hoH2k674kdJK2/UjxSw95f80LlId327Zh386A+7vCylX5zf1VhWCq5UvjLok1tK+qte/uIBjQWNw62iIhDTe+Y7pulsY0j2U5UxUPFsi/hwGqiVhf5h1lBzrCWkl8PodRYPmNDGTd0SW3OURTu/ExuyYxg/8Pzs8N8LG/SKCUPOSfHqCIff0i6HXf5GAmJUxrSEdV+Q5zmkJ8JGx5JIlQjM0r4VgjbyR0LWz4+aP6JWePzwnyLzMZXU5MkO1+TNWvhNc5QLD1M/qotxfHbw55rD+1rN2MfomFeuuio=
  bucket: innov8tionfactory.com
  acl: public_read
  region: ca-central-1
  provider: script
  script: git fetch --unshallow && git push https://innov8tionfactoryupload@innov8tionfactory.scm.azurewebsites.net:443/Innov8tionFactory.git HEAD:refs/heads/master
  verbose: true
branches:
  only:
    master